import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      style={{
        fontFamily: "auto",
        backgroundImage: "url('/images/media/dashboard.jpg')",backgroundSize: "cover", minHeight: "100vh",
        color: "white",
      }}
    >
      {children}
    </div>
  );
}
